on:
  pull_request:
    branches:
      - PublishedCopy
    types:
      [closed]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 146.88.26.91
        username: amaxinfotechwebsite
        password: Y?4g9ns38
